name: onstorage
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  fluent_ui: ^4.8.7
  settings_ui: ^2.0.2
  system_theme: ^2.3.1
  window_manager: ^0.3.9

  path: any
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  url_launcher: ^6.3.0
  disks_desktop: ^1.0.1

dev_dependencies:
  flutter_gen: any
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu-Regular.ttf
    
    - family: UbuntuMono
      fonts:
        - asset: fonts/UbuntuMono-Italic.ttf
          style: italic
        - asset: fonts/UbuntuMono-Regular.ttf

  assets:
    - lib/helper/helper

flutter_launcher_icons:
  android: true
  image_path: "logo.png"
  ios: true
  windows:
    generate: true
  macos:
    generate: true

msix_config:
  display_name: OnStorage
  publisher_display_name: Le Bao Nguyen
  identity_name: me.lebao3105.onstorage

  # https://learn.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
  capabilities: musicLibrary, picturesLibrary, videosLibrary, removableStorage, internetClient

  # https://github.com/YehudaKremer/msix/blob/main/doc/msix_version.md
  msix_version: 1.0.0.0

  logo_path: "logo.png"

  execution_alias: onstorage

  output_path: "build\\windows"