name: swifile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  fluent_ui: ^4.8.7

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  path_provider_android: ^2.2.5
  settings_ui: ^2.0.2

  path: any
  flutter_gen: any
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu-Regular.ttf
    
    - family: UbuntuMono
      fonts:
        - asset: fonts/UbuntuMono-Italic.ttf
          style: italic
        - asset: fonts/UbuntuMono-Regular.ttf

  # assets:
  #   - lib/Helper