name: onstorage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  fluent_ui: ^4.8.7

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any
  settings_ui: ^2.0.2

  path: any
  flutter_gen: any
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  system_theme: ^2.3.1
  url_launcher: ^6.3.0
  disks_desktop: ^1.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu-Regular.ttf
    
    - family: UbuntuMono
      fonts:
        - asset: fonts/UbuntuMono-Italic.ttf
          style: italic
        - asset: fonts/UbuntuMono-Regular.ttf

  assets:
    - lib/helper/helper

flutter_launcher_icons:
  android: true
  image_path: "logo.png"
  ios: true
  windows:
    generate: true
  macos:
    generate: true