name: Build release for Linux

on:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-actions@v2
        with:
          channel: stable
      
      - name: Get dependencies
        run: |
            flutter pub get
            sudo apt update -y
            sudo apt install -y ninja-build libgtk-3-dev
      
      - name: Build
        run: flutter build linux