name: Build release for Apple Darwin (iOS and macOS)

on:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-actions@v2
        with:
          channel: stable
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build for macOS
        run: flutter build macos
      
      - name: Build for Android
        run: |
          flutter build apk
          flutter build appbundle